### ISSUE TITLE
Global Extensions

### ISSUE THREAD

**Issue by Apidcloud** [scarlettgamestudio/scarlett-framework#22]
I think Global extensions of built-in objects such as Array and String should not be allowed.

An alternative would be to extend from said classes (e.g., prefix **Sugar**) and implement those extensions there.

**Comment by Apidcloud** [comment]
Or use [Lodash ](https://lodash.com/)arrays and string instead. This is probably a better solution overall.

**Comment by Apidcloud** [comment]
We can use it to replace most of the **common/utils** functions. 

Also, do we use them at all outside the library? @joafalves

**Comment by joafalves** [comment]
I don't think we need an external library but I agree that those helper functions should be scoped.

**Comment by joafalves** [comment]
> Also, do we use them at all outside the library? @joafalves

Yes, it might be useful for users (scripting)
